import { HttpCode } from "./enum.ts";

export const CONTINUE = HttpCode.CONTINUE;
export const SWITCHING_PROTOCOLS = HttpCode.SWITCHING_PROTOCOLS;
export const PROCESSING = HttpCode.PROCESSING;
export const EARLY_HINTS = HttpCode.EARLY_HINTS;

export const OK = HttpCode.OK;
export const CREATED = HttpCode.CREATED;
export const ACCEPTED = HttpCode.ACCEPTED;
export const NON_AUTHORITATIVE_INFORMATION =
    HttpCode.NON_AUTHORITATIVE_INFORMATION;
export const NO_CONTENT = HttpCode.NO_CONTENT;
export const RESET_CONTENT = HttpCode.RESET_CONTENT;
export const PARTIAL_CONTENT = HttpCode.PARTIAL_CONTENT;
export const MULTI_STATUS = HttpCode.MULTI_STATUS;
export const ALREADY_REPORTED = HttpCode.ALREADY_REPORTED;
export const IM_USED = HttpCode.IM_USED;

export const MULTIPLE_CHOICES = HttpCode.MULTIPLE_CHOICES;
export const MOVED_PERMANENTLY = HttpCode.MOVED_PERMANENTLY;
export const FOUND = HttpCode.FOUND;
export const SEE_OTHER = HttpCode.SEE_OTHER;
export const NOT_MODIFIED = HttpCode.NOT_MODIFIED;
export const USE_PROXY = HttpCode.USE_PROXY;
export const TEMPORARY_REDIRECT = HttpCode.TEMPORARY_REDIRECT;
export const PERMANENT_REDIRECT = HttpCode.PERMANENT_REDIRECT;

export const BAD_REQUEST = HttpCode.BAD_REQUEST;
export const UNAUTHORIZED = HttpCode.UNAUTHORIZED;
export const PAYMENT_REQUIRED = HttpCode.PAYMENT_REQUIRED;
export const FORBIDDEN = HttpCode.FORBIDDEN;
export const NOT_FOUND = HttpCode.NOT_FOUND;
export const METHOD_NOT_ALLOWED = HttpCode.METHOD_NOT_ALLOWED;
export const NOT_ACCEPTABLE = HttpCode.NOT_ACCEPTABLE;
export const PROXY_AUTHENTICATION_REQUIRED =
    HttpCode.PROXY_AUTHENTICATION_REQUIRED;
export const REQUEST_TIMEOUT = HttpCode.REQUEST_TIMEOUT;
export const CONFLICT = HttpCode.CONFLICT;
export const GONE = HttpCode.GONE;
export const LENGTH_REQUIRED = HttpCode.LENGTH_REQUIRED;
export const PRECONDITION_FAILED = HttpCode.PRECONDITION_FAILED;
export const PAYLOAD_TOO_LARGE = HttpCode.PAYLOAD_TOO_LARGE;
export const URI_TOO_LONG = HttpCode.URI_TOO_LONG;
export const UNSUPPORTED_MEDIA_TYPE = HttpCode.UNSUPPORTED_MEDIA_TYPE;
export const RANGE_NOT_SATISFIABLE = HttpCode.RANGE_NOT_SATISFIABLE;
export const EXPECTATION_FAILED = HttpCode.EXPECTATION_FAILED;
export const IM_A_TEAPOT = HttpCode.IM_A_TEAPOT;
export const MISDIRECTED_REQUEST = HttpCode.MISDIRECTED_REQUEST;
export const UNPROCESSABLE_ENTITY = HttpCode.UNPROCESSABLE_ENTITY;
export const LOCKED = HttpCode.LOCKED;
export const FAILED_DEPENDENCY = HttpCode.FAILED_DEPENDENCY;
export const TOO_EARLY = HttpCode.TOO_EARLY;
export const UPGRADE_REQUIRED = HttpCode.UPGRADE_REQUIRED;
export const PRECONDITION_REQUIRED = HttpCode.PRECONDITION_REQUIRED;
export const TOO_MANY_REQUESTS = HttpCode.TOO_MANY_REQUESTS;
export const REQUEST_HEADER_FIELDS_TOO_LARGE =
    HttpCode.REQUEST_HEADER_FIELDS_TOO_LARGE;
export const UNAVAILABLE_FOR_LEGAL_REASONS =
    HttpCode.UNAVAILABLE_FOR_LEGAL_REASONS;

export const INTERNAL_SERVER_ERROR = HttpCode.INTERNAL_SERVER_ERROR;
export const NOT_IMPLEMENTED = HttpCode.NOT_IMPLEMENTED;
export const BAD_GATEWAY = HttpCode.BAD_GATEWAY;
export const SERVICE_UNAVAILABLE = HttpCode.SERVICE_UNAVAILABLE;
export const GATEWAY_TIMEOUT = HttpCode.GATEWAY_TIMEOUT;
export const HTTP_VERSION_NOT_SUPPORTED = HttpCode.HTTP_VERSION_NOT_SUPPORTED;
export const VARIANT_ALSO_NEGOTIATES = HttpCode.VARIANT_ALSO_NEGOTIATES;
export const INSUFFICIENT_STORAGE = HttpCode.INSUFFICIENT_STORAGE;
export const LOOP_DETECTED = HttpCode.LOOP_DETECTED;
export const NOT_EXTENDED = HttpCode.NOT_EXTENDED;
export const NETWORK_AUTHENTICATION_REQUIRED =
    HttpCode.NETWORK_AUTHENTICATION_REQUIRED;
